name: Python application

on:
  push:
    branches: [ main, setup-project-structure, feature/auto-apply ]
  pull_request:
    branches: [ main, setup-project-structure, feature/auto-apply ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Make CI/CD workflow script executable
      run: chmod +x ./scripts/ci_cd_workflow.sh

    - name: Create, activate virtual environment, and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install beautifulsoup4
        python -m pip install pandas
        python -m pip install scikit-learn==1.3.2
      env:
        PYTHONPATH: venv/lib/python3.8/site-packages:./src:./scripts:./

    - name: List installed packages
      run: venv/bin/pip list

    - name: Check for pandas installation
      run: venv/bin/python -c "import pandas; print(pandas.__version__)"

    - name: Print Python interpreter location
      run: venv/bin/python -c "import sys; print(sys.executable)"

    - name: Print Python path
      run: venv/bin/python -c "import sys; print(sys.path)"

    - name: Check for models directory and contents
      run: ls -R models

    - name: Activate virtual environment and lint with flake8
      run: |
        source venv/bin/activate
        python -m flake8 src tests
      env:
        PYTHONPATH: venv/lib/python3.8/site-packages:./src:./scripts:./

    - name: Activate virtual environment and list installed packages before running tests
      run: |
        source venv/bin/activate
        pip list

    - name: Activate virtual environment and print Python version before running tests
      run: |
        source venv/bin/activate
        python --version

    - name: Activate virtual environment and print Python path before running tests
      run: |
        source venv/bin/activate
        python -c "import sys; print(sys.path)"

    - name: Print DATABASE_URL before running tests
      run: |
        echo "DATABASE_URL=${{ env.DATABASE_URL }}"

    - name: Create data directory
      run: mkdir -p data

    - name: Print contents of data directory before running tests
      run: |
        ls -la data/

    - name: Activate virtual environment and run tests with pytest
      run: |
        source venv/bin/activate
        python -m pytest
      env:
        PYTHONPATH: venv/lib/python3.8/site-packages:./src:./scripts:./
        DATABASE_URL: sqlite:///data/test_jobsearching_agent.db

    - name: Activate virtual environment and test prediction functionality
      run: |
        source venv/bin/activate
        python scripts/predict_job_level.py
      env:
        PYTHONPATH: venv/lib/python3.8/site-packages:./src:./scripts:./
        DATABASE_URL: sqlite:///data/test_jobsearching_agent.db
