name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Make CI/CD workflow script executable
      run: chmod +x ./scripts/ci_cd_workflow.sh

    - name: Source virtual environment and run CI/CD workflow script
      run: |
        source ./venv/bin/activate
        ./scripts/ci_cd_workflow.sh
