name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Spacy model
      run: |
        pip install spacy
        python -m spacy download en_core_web_sm

    - name: Lint with flake8
      run: |
        flake8 src tests

    - name: Run tests
      run: |
        pytest
